### ISSUE TITLE
[MusicBrainz: Import from Amazon] Tracklist is not being feeded with...

### ISSUE THREAD

**Issue by Lotheric** [Goram/MusicBrainz-Import-from-Amazon#2]
This link : 
http://www.amazon.ca/debout-%C3%89dition-deluxe-Gilles-Vigneault/dp/B00IGHT6HM

**Comment by Goram** [comment]
Puhh, looks like the vendor just misused the description for the track listing. Can you find more examples of this kind?

**Comment by Lotheric** [comment]
I tried to find another example but I can't find one. It's prolly a mistake on the distributor part using the wrong field on Amazon like you said.

**Comment by Goram** [comment]
Thanks, i´ll close this. If you find another one let me know.
