### ISSUE TITLE
Suggestion: Userscript 

### ISSUE THREAD

**Issue by madmouser1** [Goram/MusicBrainz-Import-from-Amazon#3]
hi Goram,

what about adding

// @downloadURL    https://github.com/Goram/Userscripts/raw/master/MB-Import-From-Amazon.user.js
// @updateURL      https://github.com/Goram/Userscripts/raw/master/MB-Import-From-Amazon.user.js

that way people using the userscript will automatically be updated.

**Comment by Goram** [comment]
Hi,

@version is the way to go now:

https://wiki.greasespot.net/Metadata_Block#.40version

Thx!
